name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark


    - name: Commit and Push Generated Snake
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the personal access token for authentication
  run: |
    git config --global user.name 'rajchaudar'
    git config --global user.email 'rajchaudar60@gmail.com'
    git pull origin main --rebase  # Pull the latest changes
    git add -A
    git commit -m "Generated Snake Animation" || echo "No changes to commit"
    git push https://$GITHUB_TOKEN@github.com/rajchaudar/rajchaudar.git

